spring:
  application:
    name: apollo-adminservice
  profiles:
    active: ${apollo_profile}
  datasource:
    url:  jdbc:mysql://localhost:3306/ApolloConfigDB?characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
ctrip:
  appid: 100003172
  
server:
  port: 8090
  
logging:
  file: /opt/logs/100003172/apollo-adminservice.log

apollo_profile: github
