spring:
  application:
    name: apollo-portal
  profiles:
    active: ${apollo_profile}
  datasource:
    url:  jdbc:mysql://localhost:3306/ApolloPortalDB?characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8070
  
logging:
  file: /opt/logs/100003173/apollo-portal.log

endpoints:
  health:
    sensitive: false
management:
  security:
    enabled: false
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP
apollo_profile: github




